### ISSUE TITLE
Webfont support?

### ISSUE THREAD

**Issue by ChrisKam** [fabrik42/responsive_mockups#3] opened 2015-03-02 16:42 UTC
Hi again,

after doing some 20 minute google research earlier there seems to be no support in PhantomJS 2.0 for webfonts (in my case, I use typekit for virtually all my projects). This seems to be quite the showstopper for responsive_mockups - but mabye I am overlooking something?

best wishes
Chris

**Comment by fabrik42** [comment] 2015-03-02 17:00
Yes, there is support for webfonts in PhantomJS 2.0. There have been problems in 1.9 but I could not reproduce them in 2.0.

The example screenshots in the readme are also showing custom webfonts correctly (from google web fonts as well as served by our own servers). So webfonts are generally supported and always worked when I used it.

However, I don't know if there is anything special about the way typekit loads the webfonts. Is it delayed in a special way or is it restricted to not support headless browsers?

**Comment by fabrik42** [comment] 2015-03-02 17:07
I'm closing this because I'm assuming #4 contains the solution for this problem. Please let me know if I'm mistaken.

Cheers,

Christian

**Closed as completed by fabrik42** 2015-03-02 17:07 UTC

**Comment by ChrisKam** [comment] 2015-03-03 06:50
Hi Christian,

I'm afraid that these issues are related but not the same - for instance, try running responsive_mockups with https://typekit.com/ - this is what happens:

![typekit](https://cloud.githubusercontent.com/assets/2437548/6457681/9470f3ea-c179-11e4-91c3-2b379cc3e2a7.png)

BTW I had overlooked that the webfont support is now baked in (or should be) - I only found posts on some 1.9.x branch of PhantomJS that had woff support but appeared to be discontinued. Apparently ,these issues should have been resolved by now... but not for typekit, which is super widely used. If you like, I can try to isolate this issue and move it towards the main phantomjs repo - if you are getting the same missing fonts.

**Comment by ChrisKam** [comment] 2015-03-03 09:14
..getting there. It works with phantomjs 1.9.2, only the font-weights are broken for me atm. Should be easy enough to fix though... 

![typekit](https://cloud.githubusercontent.com/assets/2437548/6459326/f52f16ee-c18d-11e4-96e4-d919a93f897f.png)

**Comment by fabrik42** [comment] 2015-03-04 16:21
Awesome! I'm curious what you'll find out. :)
